services:
    mongo:
        image: mongo:latest
        container_name: ddd-mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: scoth
            MONGO_INITDB_ROOT_PASSWORD: tiger1234
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        networks:
          - ddd-network

    postgres:
        image: postgres:latest
        container_name: ddd-postgres
        environment:
          POSTGRES_USER: johndoe
          POSTGRES_PASSWORD: somew0rds
          POSTGRES_DB: postgres
        ports:
          - "5432:5432"
        volumes:
          - postgres-data:/var/lib/postgres/data
        networks:
          - ddd-network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: ddd-pgadmin
        environment:
          PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
          PGADMIN_DEFAULT_PASSWORD: 123456
        ports:
          - "5050:80"
        depends_on:
          - postgres
        networks:
          - ddd-network

volumes:
    postgres-data:
        driver: local
    mongo-data:
        driver: local
    mongo-config:
        driver: local

networks:
  ddd-network:
    driver: bridge